BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "hoca" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Ad"	TEXT NOT NULL,
	"Soyad"	TEXT NOT NULL,
	"Kullanici_adi"	TEXT NOT NULL,
	"Sifre"	INTEGER NOT NULL,
	"Telefon"	INTEGER NOT NULL,
	"D_Tarih"	DATE
);
CREATE TABLE IF NOT EXISTS "sporcu" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Ad"	TEXT NOT NULL,
	"Soyad"	TEXT NOT NULL,
	"Kullanici_adi"	TEXT NOT NULL,
	"Sifre"	INTEGER NOT NULL,
	"Telefon"	INTEGER NOT NULL,
	"D_Tarih"	DATE,
	"Boy"	INTEGER NOT NULL,
	"Kilo"	INTEGER NOT NULL
);
COMMIT;
